Tools/Applications/RegistrationAdminTool/RegistrationAdminTool/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Matchnet.Content.ValueObjects.Registration;
using RegistrationAdminTool.Configuration;
using RegistrationAdminTool.Managers;
using RegistrationAdminTool.Models;

namespace RegistrationAdminTool.Controllers
{
//    [SparkAuthorize(Operation = Enums.Operations.Access)]
    public class TemplateController : BaseController
    {
        //
        // GET: /Template/
        public ActionResult Index()
        {
            TemplateManager templateManager = new TemplateManager();
            return View("Templates", templateManager.GetTemplateViewModel());        
        }        

        public ActionResult CreateTemplate()
        {
            TemplateManager templateManager = new TemplateManager();
            return View("NewTemplate", templateManager.GetNewTemplateViewModel());            
        }

        [HttpPost]
        public ActionResult SaveTemplate(SaveTemplateModel saveTemplateModel)
        {
            TemplateManager templateManager = new TemplateManager();
            TemplateModel templateModel = null;
            if (ModelState.IsValid)
            {
                templateModel = templateManager.SaveTemplateModel(saveTemplateModel);
            }

            if (null != templateModel && templateModel.ID > 0)
            {
                TemplateViewModel templateViewModel = templateManager.GetTemplateViewModel();
                templateViewModel.SuccessMessage = templateModel.SuccessMessage;
                return View("Templates", templateViewModel);
            }
            else
            {
                var model = templateManager.GetNewTemplateViewModel();
                model.ErrorMessage = (null != templateModel)? templateModel.ErrorMessage : "Error saving template.";
                model.TemplateType = saveTemplateModel.TemplateType;
                model.Name = saveTemplateModel.Name;
                model.SiteId = saveTemplateModel.SiteId;
                return View("NewTemplate", model);
            }
        }

        public ActionResult RemoveTemplate(int regTemplateId, int siteId)
        {
            TemplateManager templateManager = new TemplateManager();
            TemplateViewModel templateViewModel=templateManager.RemoveTemplateModel(regTemplateId, siteId);
            return View("Templates", templateViewModel);
        }
    }
}

Tools/Applications/RegistrationAdminTool/RegistrationAdminTool/Views/Template/NewTemplate.cshtml
@using RegistrationAdminTool.Models
@model CreateTemplateViewModel
@{
    ViewBag.Title = "NewTemplate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ Html.BeginForm("SaveTemplate", "Template", FormMethod.Post); }
    <h2>Create a Template</h2>
    <hr />
<div id="pageError" style="color: red">
    @Model.ErrorMessage
</div>
<div>
    <ul class="template-name">
        <li>
            <div><strong>Site:</strong></div>
            <div>
                <div id="spnSiteListError" style="color: red">
                    @Html.ValidationMessageFor(m => m.SiteId)
                </div>
                @Html.DropDownListFor(m => m.SiteId, Model.Sites, new { id = "newTemplateSiteList" })
            </div>
        </li>
        <li>
            <div><strong>Type:</strong></div>
            <div>
                <div id="spnTemplateTypeListError" style="color: red">
                    @Html.ValidationMessageFor(m => m.TemplateType)                
                </div>
                @Html.DropDownListFor(m => m.TemplateType, Model.TemplateTypes, new { id = "newTemplateTypeList" })
            </div>
        </li>
        <li>
            <div><strong>Template Name:</strong></div>
            <div>
                <div id="spnTemplateNameError" style="color: red">
                    @Html.ValidationMessageFor(m => m.Name)                
                </div>
                @Html.TextBoxFor(m => m.Name, new { id = "txtTemplateName", style="width:170px;", maxlength="30" })
            </div>
        </li>
        <li>
            <br/>
            <input type="submit" id="btnSaveTemplate" value="Save" />            
        </li>
        <li>
            <p><a href="/gettemplates/">Back To All Templates</a></p>
        </li>
    </ul>
</div>
@section scripts
{
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery.lightbox_me.js")"></script>
}

@{ Html.EndForm(); }

Tools/Applications/RegistrationAdminTool/RegistrationAdminTool/Views/Template/Templates.cshtml
@using Matchnet.Content.ValueObjects.Registration
@using RegistrationAdminTool.Models
@model TemplateViewModel
           
@{
    ViewBag.Title = "Templates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Template Manager</h2>
<hr />
<div id="pageConf" style="color: blue">
    @Model.SuccessMessage
</div>
<div id="pageError" style="color: red">
    @Model.ErrorMessage
</div>
<div>
    <div>
        <strong>Site</strong>
        <br />
        @Html.DropDownListFor(m=> m.SiteId, Model.Sites, new { id = "siteList" })
    </div>
    <div>
        <strong>Template Type</strong>
        <br />
        @Html.DropDownListFor(m => m.TemplateType, Model.TemplateTypes, new { id = "templateTypeList" })
    </div>
    <button type="button" id="btnViewSelect">View</button>
</div>

<div>
    @foreach (SelectListItem site in Model.Sites.Skip(1))
    {    
        foreach (List<TemplateModel> templateModels in Model.Templates[new SiteModel(Int32.Parse(site.Value), site.Text)].Values)
        {
            <div id="@site.Value-@templateModels[0].Type" class="templateSelectDiv" style="display: none;">
                <strong>@templateModels[0].Type</strong>
                <br />
                <select id="@site.Value-@templateModels[0].Type" name="@site.Value-@templateModels[0].Type" class="templateSelects" multiple="multiple">
                    @foreach (TemplateModel templateModel in templateModels)
                    {
                        <option value="@templateModel.ID">@templateModel.Name</option>
                    }
                </select>
            </div>
        }
    }
</div>

<div id="templates" style="display: none;">
    <strong>Template Name</strong>
    <br />
    <select id="templatesList" name="TemplateId" multiple="multiple">
    </select>
</div>

<div id="templateDetails" style="display: none;"></div>

<div>
<p><a href="/createnewtemplate/">Create New Template</a></p>
</div>

@section scripts
{    
    <script type="text/javascript" src="@Url.Content("/Scripts/mustache.js")"></script>
    <script type="text/html" id="detailsMustache">
        <div class="desc">
            <div class="sectionTitle">
                <strong>Description</strong>
            </div>
            <span id="desc"></span>
        </div>
        <div class="features">
            <div class="sectionTitle">
                <strong>Features & Settings</strong>
            </div>
            <ul>
                <li>
                    <div>
                        Id:
                    </div>
                    <div>
                        <span id="templateId">{{id}}</span>
                    </div>
                </li>
                <li class="even">
                    <div>
                        Name:
                    </div>
                    <div>
                        <span id="templateName">{{name}}</span>
                    </div>
                </li>
                <li>
                    <div>
                        Template Type:
                    </div>
                    <div>
                        <span id="templateType">{{type}}</span>
                    </div>
                </li>
                <li class="even">
                    <div>
                        Site Id:
                    </div>
                    <div>
                        <span id="templateSiteId">{{siteId}}</span>
                    </div>
                </li>
            </ul>
        </div>
        <div class="action">
            <button type="button" id="btnRemoveTemplate">Remove</button>
        </div>
        <input type="hidden" id="regTemplateId" value="{{id}}"/>       
        <input type="hidden" id="regTemplateSiteId" value="{{siteId}}"/>       
    </script>
   
    <script type="text/javascript">
        var allTemplates = {};
        function Template(id, name, type, siteId)
        {
            this.id = id;
            this.name = name;
            this.type = type;
            this.siteId = siteId;
        }

        $(document).ready(function () {
            $("#btnViewSelect").click(function () {
                $(".templateSelectDiv").hide();
                var site = $("#siteList option:selected").val();
                var type = $("#templateTypeList option:selected").text();
                $("#" + site + "-" + type).show();
            });

            $(".templateSelects").change(function () {
                $("#templateDetails").hide();
                var val = $(this).find("option:selected").val();
                var templateData = allTemplates[val];
                var template = $("#detailsMustache").text();
                $("#templateDetails").html(Mustache.to_html(template, templateData)).show();
            });

            $("#btnRemoveTemplate").live("click", function () {
                var templateId = $("#regTemplateId").val();
                var templateSiteId = $("#regTemplateSiteId").val();
                window.location.href = "/removetemplate/" + templateId + "/" + templateSiteId;
            });
        });
    </script>

        <script type="text/javascript">
            $(document).ready(function () {
    @foreach (SiteModel siteModel in Model.Templates.Keys)
    {
        foreach (List<TemplateModel> templateModels in Model.Templates[siteModel].Values)
        {
            foreach (TemplateModel templateModel in templateModels)
            {
            <text>
            allTemplates[@templateModel.ID] = new Template(@templateModel.ID, '@templateModel.Name', '@templateModel.Type', @templateModel.SiteID);
            </text>
            }
        }
    }
            });
        </script>
}
