web/Spark.Registration.Adventist/Spark.Registration.Adventist/Controllers/PixelController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Spark.Registration.Adventist.Interfaces.Adapters;
using Spark.Registration.Adventist.Managers;

namespace Spark.Registration.Adventist.Controllers
{
    public class PixelController : BaseController
    {
        public PartialViewResult Index(string pageName)
        {
            List<string> pixels = new PixelManager().RetrievePixels(pageName);
            return PartialView("Pixels", pixels);
        }
    }
}

web/Spark.Registration.Adventist/Spark.Registration.Adventist/Views/Confirmation/Confirmation1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.BodyClass = "p-reg-conf";
    
    //DNS prefetching for improved performance. More reading: http://html5boilerplate.com/docs/DNS-Prefetching/
    string[] DNSArray = { "ajax.googleapis.com", "www.adventistsinglesconnection.com", "mpsnare.iesnare.com" };
    ViewBag.DNSPrefetch = DNSArray;
}

<header role="banner">
    <a href="/" class="logo"><img src="@Url.Content("~/RegContent/Images/logo-header_reg-gc.png")" alt="" class="logo"></a>
</header>

<div id="container" class="cf">
	@*<nav role="navigation"></nav>*@
	<nav class="nav-alternative"></nav>

    <div role="content">

        <h1>Congratulations! You are now a member of Adventist Singles!</h1>
        <ul>
            <li role="marketing">
                <span class="sprite-imgs-confirmation-sub"></span>
                <div class="info">
                    <h2>Become a Subscriber!</h2>
                    <div class="cta">
                        <a class="btn-icon link-primary" href="@ViewBag.SubscriptionLink">
                            <span class="btn-icon-icon">
                                <img src="@Url.Content("~/RegContent/Images/icon-secure.png")" alt="">
                            </span><span class="btn-icon-text">Upgrade Now!</span>
                        </a>
                    </div>
                    <p class="tag-line">Become an Adventist Singles subscriber and have a much better shot at finding love!</p>
                </div>
            </li>
            <li role="marketing">
                <span class="sprite-imgs-confirmation-intro"></span>
                <div class="info">
                    <h2>Introduce Yourself!</h2>
                    <div class="cta">
                        <a class="btn link-secondary" href="http://@ViewBag.BedrockHost/profile/">Complete Your Profile</a>
                    </div>
                    <p class="tag-line">Introduce yourself by answering a few questions and uploading some fun photos!</p>
                </div>
            </li>
            <li role="marketing">
                <span class="sprite-imgs-confirmation-browse"></span>
                <div class="info">
                    <h2>Start Browsing Now!</h2>
                    <div class="cta">
                        <a class="btn link-secondary" href="http://@ViewBag.BedrockHost/search/advanced.html">Search Your Matches</a>
                    </div>
                    <p class="tag-line">Find Adventist Singles in your area by checking out who’s online at this very minute!</p>
                </div>
            </li>
        </ul>

    @*<section role="content-main" class="editorial">
	    <h1>You're So Close &ndash; Don't Stop Now!</h1>
	    <p class="intro">Mazel tov, you are now a JDate member. However, you should become a subscribing member if you're serious about finding your Beshert! Why? Because you will need a JDate subscription in order to:</p>
	    <ul class="ui-arrows">
		    <li>Send an email</li>
		    <li>Receive an email</li>
		    <li>Chat on IM</li>
		    <li>Post and reply on Message Boards</li>
		    <li>Send personalized eCards</li>
	    </ul>
	    <p class="">And a whole lot more!</p>
        <p class="block-text">You've taken a great first step by signing up. Now take the next step on your quest for love and become a subscriber! Simply pick a plan, start communicating with the thousands of Jewish singles near you, and let the excitement begin!</p>

	    <div class="cta">
		    <a class="btn-icon link-primary" href="@ViewBag.SubscriptionLink">
                <span class="btn-icon-icon">
                    <img src="@Url.Content("~/RegContent/Images/icon-secure.png")" alt="" />
                </span><span class="btn-icon-text">Become a Subscriber</span>
            </a>
	    </div>
    </section>

    <aside role="content-secondary">
	    <section>
		    <h1>Ready to introduce yourself? </h1>
		    <img alt="JD Profile" src="@Url.Content("~/RegContent/Images/scrn-profile.jpg")" title="JD Profile" />
		    <p>Introduce yourself by uploading some fun photos and writing your About Me essay. Need help? We've got tips along the way!</p>
		    <div class="cta">
			    <a class="btn link-secondary" href="http://@ViewBag.BedrockHost/applications/memberprofile/ViewProfile.aspx?Mode=Edit">Complete Your Profile</a>
		    </div>
	    </section>
	    <section>
		    <h1>Can't wait to see your matches?</h1>
		    <img alt="Profiles of Your Matches" src="@Url.Content("~/RegContent/Images/scrn-matches.jpg")" title="Profiles of Your Matches" />
		    <p>Start browsing the profiles of Your Matches. See someone you like? Give ‘em a Click! or send a Flirt!</p>
		    <div class="cta">
			    <a class="btn link-secondary" href="http://@ViewBag.BedrockHost/Applications/Search/SearchResults.aspx?NavPoint=sub">Search Your Matches</a>
		    </div>
	    </section>
    </aside>*@

    </div>

</div>

@Html.Partial("_Footer")

@Html.Action("Index", "Pixel", new {pageName = "registrationconfirmation"})

@* Put section overrides here *@
@section BottomJavaScript{
<script src="@Url.Content("~/RegContent/Scripts/Libs/LAB.min.js")"></script>
<script>
	var spark = spark || {};
	//DO NOT REMOVE. This line should occur before loading Omniture.js file. 
    var s_account = '@ViewBag.OmnitureAccountName';
    
	$LAB
    .setOptions({AlwaysPreserveOrder:true})
	.script("https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js")
	.wait(function(){
		if (typeof jQuery != "function") return "@Url.Content("~/RegContent/Scripts/Libs/jQuery/jquery-1.7.2.min.js")";
	})
	.script("@Url.Content("~/RegContent/Scripts/main.js")")
	.wait(function(){
		$(function(){
			//actual js for confirm page
			var titleText = '';
			$('h1, h2').each(function() {
				titleText  = $(this).text().replace(/ (\S+)$/,'&nbsp;$1');
				$(this).html(titleText);
			});
		});
	})	
	.script("@Url.Content("~/RegContent/Scripts/Libs/Omniture.js")")
	.wait(function () {
	    @Html.Action("Index", "Omniture", new { pageName = "registrationconfirmation" })
	});
</script>
}

web/Spark.Registration.Adventist/Spark.Registration.Adventist/Views/Confirmation/MobileConfirmation1.cshtml
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.BodyClass = "ui-mobile-viewport";

    //DNS prefetching for improved performance. More reading: http://html5boilerplate.com/docs/DNS-Prefetching/
    string[] DNSArray = { "code.jquery.com", "www.jdate.com", "m.jdate.com" };
    ViewBag.DNSPrefetch = DNSArray;
}

<div data-role="page" data-theme="c" class="m_reg_complete" data-title="JDate - Registration Confirmation">
    <header data-theme="b" data-role="header">
        <h1 class="ir logo">JDate</h1>
    </header>

    <div data-role="content" class="ui-content" role="main">
        <h2 class="c_headTitle">Mazel Tov!</h2>
        
        <p class="c_text;">You've successfully joined JDate. Connect with smart, successful Jewish singles...and maybe even find your Besheret!</p>

        <div data-theme="d" class="divGals" id="gals" >
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Woman1.png")" style="width:88px; height:88px;" /></div>
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Woman2.png")" style="width:88px; height:88px;" /></div>
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Woman3.png")" style="width:88px; height:88px;" /></div>
        </div>

        <div data-theme="d" class="divGuys" id="guys">
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Man1.png")" style="width:88px; height:88px;" /></div>
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Man2.png")" style="width:88px; height:88px;" /></div>
            <div class="imgDiv"><img src="@Url.Content("~/RegContent/Images/Mobile_Man3.png")" style="width:88px; height:88px;" /></div>
        </div>

        <div class="divMolA">
            <a id="molA" class="molA" data="http://@ViewBag.MOSHost/membersonline/results"> <img src="@Url.Content("~/RegContent/Images/icon_green_online.png")" style="height:10px;" />  @ViewBag.MembersOnlineCount members online now</a>
        </div>

        <div class="divFnprofile">
            <a id="fnProfile" class="fnProfile" data="http://@ViewBag.MOSHost/membersonline/results">Add Photos & finish my profile</a>
        </div>

        @*<p class="c_des">Are you ready to get serious about finding your <em>Beshert</em>?</p>*@
        <div class="downloadBtn">
            <a href="http://m.jdate.com/mobile" class="downloadLink"data-ajax="false">Download The App</a>
        </div>

        <a  id="aSubNow" class="aSubNow" data-ajax="false">Subscribe now for full access!</a> <br />

    </div>

    @Html.Partial("_MobileFooter")

</div>

@Html.Action("Index", "Pixel", new {pageName = "registrationconfirmation"})

<!-- /page -->


@* Put section overrides here *@
@section HeadUI{
    @Html.Partial("_MobileMetaTags")
    <link rel="stylesheet" href="@Url.Content("~/RegContent/CSS/reg.mobile.css")" />
    <link rel="stylesheet" href="@Url.Content("~/RegContent/CSS/m_confimation.css")" />
    @* All JavaScript at the bottom, except Modernizr, jQuery and jQuery mobile *@
    <script src="@Url.Content("~/RegContent/Scripts/Libs/modernizr.2.6.custom.js")"></script>
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>
    <script>
        $.mobile.ajaxEnabled = false;
    </script>

}

@section BottomJavaScript{
<script src="@Url.Content("~/RegContent/Scripts/Libs/LAB.min.js")"></script>
<script>
    var spark = spark || {};
    //DO NOT REMOVE. This line should occur before loading Omniture.js file.
    var s_account = '@ViewBag.OmnitureAccountName';
    $LAB
    .setOptions({ AlwaysPreserveOrder: true })
    .script("@Url.Content("~/RegContent/Scripts/mobile-main.js")")
	.script("@Url.Content("~/RegContent/Scripts/Libs/Omniture.js")")
	.wait(function () {
	    @Html.Action("Index", "Omniture", new { pageName = "registrationconfirmation" })
	});

    if (sessionStorage.getItem("gendermask") == '1') {
        document.getElementById('gals').style.display = "block";
    }
    else if (sessionStorage.getItem("gendermask") == '2') {
        document.getElementById('guys').style.display = "block";
    }



    // fire custom omniture events

     $('#molA').bind('click', function() { 

         s.events = "event18";
         fireProp14('MOS RegComplete - Online Now', 'http://@ViewBag.MOSHost/membersonline/results');
     });

     $('#fnProfile').bind('click', function () {

         fireProp14('MOS RegComplete - Complete Profile', 'http://@ViewBag.MOSHost/profile/@ViewBag.NewMemberId');
    });

    $('#aSubNow').bind('click', function () {
        fireProp14('MOS RegComplete - Subscribe', 'http://@ViewBag.MOSHost/subscription/subscribe?prtid=4160'); 
    });


    function fireProp14(value, distination) {

      try {

              var s = s_gi('sparkjdatecom');
              s.prop14 = value;
              s.tl();
                window.setTimeout(function() {
                    document.location = distination;
                }, 1000)
            

        }
        catch (err)
        { }
    }



    //alert("gendermask = " + sessionStorage.getItem("gendermask"));

</script>
}

@* Empty IE6Chromeframe section *@
@section IE6Chromeframe{}>